CREATE TABLE DEPARTMENTS(	
    DEPARTMENT_ID NUMBER(10) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL ,
    DEPARTMENT_NAME	NVARCHAR2(200) NOT NULL,
    MANAGER_ID NUMBER(10) NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID)
);	
	
CREATE TABLE JOBS(	
    JOB_ID	NUMBER(10) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL ,
    JOB_TITLE NVARCHAR2(100) NOT NULL
);

ALTER TABLE JOBS 
ADD CONSTRAINT JOB_PK PRIMARY KEY (JOB_ID);

CREATE TABLE EMPLOYEES(	
    EMPLOYEE_ID	NUMBER(10) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL ,
    FIRST_NAME NVARCHAR2(100) NOT NULL,
    LAST_NAME NVARCHAR2(100) NOT NULL,
    EMAIL NVARCHAR2(100) NOT NULL,
    PHONE_NUMBER NVARCHAR2(20) DEFAULT NULL,
    DATE_OF_BIRTH DATE DEFAULT NULL,
    HIRE_DATE DATE NOT NULL,
    JOB_ID NUMBER(10) NOT NULL,
    SALARY NUMBER(10,2) NOT NULL,
    MANAGER_ID NUMBER(10) DEFAULT NULL,
    DEPARTMENT_ID NUMBER(10) DEFAULT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),	
    CONSTRAINT EMPLOYEE_UNIQUE UNIQUE(EMAIL),	
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),	
    CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);	

CREATE TABLE JOB_HISTORY(
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID NUMBER(10) NOT NULL,
    DEPARTMENT_ID NUMBER(10) DEFAULT NULL,  
    CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    CONSTRAINT FK_JOB_HISTORY_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT FK_JOB_HISTORY_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT CHECK_START_DATE_END_DATE CHECK(START_DATE < END_DATE)
);

ALTER TABLE JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);


CREATE TABLE USERS(
    USER_ID NUMBER(10)GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE_ID NUMBER(10) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
 
ALTER TABLE USERS
ADD CONSTRAINT USER_NAME_UNIQUE UNIQUE(USER_NAME);

CREATE TABLE ROLES(
    ROLE_ID NUMBER(10) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID)
);


CREATE TABLE TOKENS(
    TOKEN_ID NUMBER(10)GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    TOKEN_TYPE VARCHAR2(100) NOT NULL,
    EXPIRATION_DATE TIMESTAMP,
    REVOKED NUMBER NOT NULL,
    EXPIRED NUMBER NOT NULL,
    USER_ID NUMBER(10) NOT NULL,
    CONSTRAINT TOKEN_PK PRIMARY KEY (TOKEN_ID),
    CONSTRAINT TOKEN_UNIQUE UNIQUE(TOKEN),
    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);