package com.hr.management.mapper;

import com.hr.management.model.Departments;
import com.hr.management.model.DepartmentsExample;
import java.util.List;

import com.hr.management.model.DepartmentsFull;
import org.apache.ibatis.annotations.Param;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13 :30:33 ICT 2024
     */
    long countByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insert(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insertSelective(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    List<Departments> selectByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    Departments selectByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Departments row, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExample(@Param("row") Departments row, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKeySelective(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKey(Departments row);

    Departments getDepartmentByManagerId(Long managerId);

    List<Departments> getDepartmentByName(String departmentName);

    List<DepartmentsFull> getDepartmentsWithManagerName();

    DepartmentsFull getDepartmentsWithManagerNameById(Long id);

    List<DepartmentsFull> getDepartmentsWithManagerNameByKeyWord(String keyword);
}