package com.hr.management.mapper;

import com.hr.management.model.JobHistory;
import com.hr.management.model.JobHistoryExample;
import com.hr.management.model.JobHistoryFull;
import com.hr.management.model.JobHistoryKey;

import java.time.LocalDate;
import java.util.List;

import com.hr.management.request.JobHistoryRequest;
import org.apache.ibatis.annotations.Param;

public interface JobHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    long countByExample(JobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByExample(JobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByPrimaryKey(@Param("employeeId") Long employeeId, 
    @Param("startDate") LocalDate startDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insert(JobHistoryRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insertSelective(JobHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    List<JobHistory> selectByExample(JobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    JobHistory selectByPrimaryKey(JobHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExampleSelective(@Param("row") JobHistoryFull row, @Param("example") JobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExample(@Param("row") JobHistory row, @Param("example") JobHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKeySelective(JobHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKey(JobHistoryFull row);

    List<JobHistoryFull> getJobHistoryFullByEmployeeId(Long employeeId);

    List<JobHistoryFull> getJobHistoryDetail();

    JobHistoryFull getJobHistoryFullByEmployeeIdDate(@Param("employeeId") Long employeeId, 
    @Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);

    JobHistoryFull getJobHistoryFullByEmployeeIdStartDate(@Param("employeeId") Long employeeId, 
    @Param("startDate") LocalDate startDate);

    JobHistory selectByPrimaryKeyCustom(@Param("employeeId") Long employeeId, 
    @Param("startDate") LocalDate startDate);
}