package com.hr.management.mapper;

import com.hr.management.model.Tokens;
import com.hr.management.model.TokensExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    long countByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int deleteByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insert(Tokens row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int insertSelective(Tokens row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    List<Tokens> selectByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    Tokens selectByPrimaryKey(Long tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExampleSelective(@Param("row") Tokens row, @Param("example") TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByExample(@Param("row") Tokens row, @Param("example") TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKeySelective(Tokens row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKENS
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    int updateByPrimaryKey(Tokens row);
}