package com.hr.management.model;

import com.hr.management.request.DepartmentsRequest;
import jakarta.validation.constraints.NotEmpty;
import lombok.Builder;

@Builder
public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    @NotEmpty(message = "Department name is required")
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */

    @NotEmpty(message = "manager ID is required")
    private Long managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @return the value of DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @param departmentId the value for DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @return the value of DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @param departmentName the value for DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.MANAGER_ID
     *
     * @return the value of DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.MANAGER_ID
     *
     * @param managerId the value for DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    public static Departments fromDepartmentRequest(DepartmentsRequest departmentsRequest){
        return Departments
                .builder()
                .departmentName(departmentsRequest.getDepartmentName())
                .managerId(departmentsRequest.getManagerId())
                .build();
    }
}