package com.hr.management.model;

import java.math.BigDecimal;
import java.util.Date;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.EMAIL
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.DATE_OF_BIRTH
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.SALARY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @return the value of EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @param employeeId the value for EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.FIRST_NAME
     *
     * @return the value of EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.FIRST_NAME
     *
     * @param firstName the value for EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.LAST_NAME
     *
     * @return the value of EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.LAST_NAME
     *
     * @param lastName the value for EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.EMAIL
     *
     * @return the value of EMPLOYEES.EMAIL
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.EMAIL
     *
     * @param email the value for EMPLOYEES.EMAIL
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.PHONE_NUMBER
     *
     * @return the value of EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.PHONE_NUMBER
     *
     * @param phoneNumber the value for EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.DATE_OF_BIRTH
     *
     * @return the value of EMPLOYEES.DATE_OF_BIRTH
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for EMPLOYEES.DATE_OF_BIRTH
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.HIRE_DATE
     *
     * @return the value of EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.HIRE_DATE
     *
     * @param hireDate the value for EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.JOB_ID
     *
     * @return the value of EMPLOYEES.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.JOB_ID
     *
     * @param jobId the value for EMPLOYEES.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.SALARY
     *
     * @return the value of EMPLOYEES.SALARY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.SALARY
     *
     * @param salary the value for EMPLOYEES.SALARY
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.MANAGER_ID
     *
     * @return the value of EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.MANAGER_ID
     *
     * @param managerId the value for EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @return the value of EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @param departmentId the value for EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
}