package com.hr.management.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.Date;

public class JobHistoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */

    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.START_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
    @NotNull(message = "Start date is required")
    private LocalDate startDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @return the value of JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @param employeeId the value for JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.START_DATE
     *
     * @return the value of JOB_HISTORY.START_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.START_DATE
     *
     * @param startDate the value for JOB_HISTORY.START_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }
}