package com.hr.management.model;

public class Jobs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.JOB_TITLE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String jobTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.JOB_ID
     *
     * @return the value of JOBS.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.JOB_ID
     *
     * @param jobId the value for JOBS.JOB_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.JOB_TITLE
     *
     * @return the value of JOBS.JOB_TITLE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.JOB_TITLE
     *
     * @param jobTitle the value for JOBS.JOB_TITLE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }
}