package com.hr.management.model;

import java.util.Date;

public class Tokens {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.TOKEN_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long tokenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.TOKEN
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.TOKEN_TYPE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private String tokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.EXPIRATION_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Date expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.REVOKED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Short revoked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.EXPIRED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Short expired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOKENS.USER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.TOKEN_ID
     *
     * @return the value of TOKENS.TOKEN_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.TOKEN_ID
     *
     * @param tokenId the value for TOKENS.TOKEN_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setTokenId(Long tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.TOKEN
     *
     * @return the value of TOKENS.TOKEN
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.TOKEN
     *
     * @param token the value for TOKENS.TOKEN
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.TOKEN_TYPE
     *
     * @return the value of TOKENS.TOKEN_TYPE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public String getTokenType() {
        return tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.TOKEN_TYPE
     *
     * @param tokenType the value for TOKENS.TOKEN_TYPE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType == null ? null : tokenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.EXPIRATION_DATE
     *
     * @return the value of TOKENS.EXPIRATION_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.EXPIRATION_DATE
     *
     * @param expirationDate the value for TOKENS.EXPIRATION_DATE
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.REVOKED
     *
     * @return the value of TOKENS.REVOKED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Short getRevoked() {
        return revoked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.REVOKED
     *
     * @param revoked the value for TOKENS.REVOKED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setRevoked(Short revoked) {
        this.revoked = revoked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.EXPIRED
     *
     * @return the value of TOKENS.EXPIRED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Short getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.EXPIRED
     *
     * @param expired the value for TOKENS.EXPIRED
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setExpired(Short expired) {
        this.expired = expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOKENS.USER_ID
     *
     * @return the value of TOKENS.USER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOKENS.USER_ID
     *
     * @param userId the value for TOKENS.USER_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}