package com.hr.management.model;

import com.hr.management.request.UsersRequest;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Users {
    private Long userId;
    private String userName;
    private String password;
    private Long roleId;
    public Long getUserId() {
        return userId;
    }
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return userName;
    }
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ROLE_ID
     *
     * @param roleId the value for USERS.ROLE_ID
     *
     * @mbg.generated Mon Sep 16 13:30:33 ICT 2024
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public static Users fromUserRequest(UsersRequest usersRequest){
        return Users.builder()
                .userName(usersRequest.getUserName())
                .password(usersRequest.getPassword())
                .roleId(usersRequest.getRoleId())
                .build();
    }



}